export interface Structure {
  name: string;
  emoji?: string;
  simple: string;
  full: string;
  color: string;
}

export interface ModuleData {
  slug: string;
  uid: string;
  title: string;
  subtitle: string;
  accent: string;
  intro: string;
  structures: Structure[];
}

export const MODULES: ModuleData[] = [
  {
    slug: "celula",
    uid: "0d9f7f4257224975b2ef83a283709b2f",
    title: "Célula Animal",
    subtitle: "🔬 Biología celular",
    accent: "#4ade80",
    intro: "Explorá un modelo 3D real de una célula eucariota animal. Tocá los puntos ⓘ en el modelo o las estructuras de abajo.",
    structures: [
      { name: "Núcleo", emoji: "🔵", color: "#3b82f6", simple: "Es el 'cerebro' de la célula — guarda la información genética.", full: "Organela delimitada por la envoltura nuclear (doble membrana con poros). Contiene el ADN organizado en cromosomas y el nucléolo. Dirige la transcripción del ARNm y por ende toda la síntesis proteica." },
      { name: "Mitocondria", emoji: "🟠", color: "#f97316", simple: "Produce la energía que necesita la célula para vivir.", full: "Organela de doble membrana con crestas internas. Realiza la fosforilación oxidativa (cadena respiratoria) para sintetizar ATP. Posee su propio ADN circular, evidencia de origen endosimbiótico." },
      { name: "Retículo Endoplasmático", emoji: "🟣", color: "#a855f7", simple: "Es como una red de caminos que transporta proteínas por la célula.", full: "Sistema de membranas interconectadas. El RER (rugoso) tiene ribosomas adosados y sintetiza proteínas de secreción; el REL (liso) sintetiza lípidos y detoxifica sustancias." },
      { name: "Aparato de Golgi", emoji: "🟡", color: "#eab308", simple: "Empaqueta y envía proteínas a donde se necesitan, como un correo postal.", full: "Conjunto de cisternas membranosas apiladas (cis, medial, trans). Modifica proteínas con azúcares (glicosilación), las clasifica y envía en vesículas hacia la membrana plasmática o lisosomas." },
      { name: "Lisosoma", emoji: "🩷", color: "#ec4899", simple: "Digiere y recicla los desechos y partes viejas de la célula.", full: "Vesícula con enzimas hidrolíticas activas a pH ácido (~4,5). Realiza autofagia (recicla orgánulos dañados) y heterofagia (degrada material externo). Su ruptura puede desencadenar apoptosis." },
      { name: "Ribosoma", emoji: "🟢", color: "#22c55e", simple: "Fabrica las proteínas que la célula necesita para funcionar.", full: "Complejo ARN-proteínas formado por subunidad mayor (60S) y menor (40S). Lee el ARNm y sintetiza cadenas polipeptídicas mediante la traducción. Puede estar libre en citoplasma o unido al RER." },
      { name: "Membrana Plasmática", emoji: "🫧", color: "#14b8a6", simple: "Es la 'piel' de la célula: controla qué entra y qué sale.", full: "Bicapa fosfolipídica con proteínas integrales y periféricas (modelo mosaico fluido). Regula el transporte de iones y moléculas mediante canales, bombas y transporte activo/pasivo." },
      { name: "Centrosoma", emoji: "⭐", color: "#f43f5e", simple: "Organiza la división celular y ayuda a mover los cromosomas.", full: "Par de centríolos rodeados de material pericentriolar. Nuclea los microtúbulos del huso mitótico durante la división. Clave en la organización del citoesqueleto y la formación de cilios." },
      { name: "Vacuola", emoji: "🔷", color: "#06b6d4", simple: "Almacena agua, nutrientes o desechos como un depósito.", full: "Vesícula membranosa (tonoplasto). En células animales son pequeñas y temporales; participan en endocitosis/exocitosis. Regulan la osmosis y eliminan sustancias de desecho." },
      { name: "Citoesqueleto", emoji: "🕸️", color: "#94a3b8", simple: "Es como los huesos de la célula: le da forma y permite que se mueva.", full: "Red de filamentos proteicos: microtúbulos (tubulina), filamentos de actina y filamentos intermedios. Mantiene la forma celular, posiciona orgánulos, permite la migración y la división celular." },
    ],
  },
  {
    slug: "adn",
    uid: "212e5422645f4432a61dc2f3aac3c8c8",
    title: "ADN & Genética",
    subtitle: "🧬 Biología molecular",
    accent: "#60a5fa",
    intro: "Explorá la doble hélice del ADN en 3D. Tocá los puntos ⓘ en el modelo o las estructuras de abajo.",
    structures: [
      { name: "Doble Hélice", emoji: "🧬", color: "#3b82f6", simple: "La forma retorcida del ADN, como una escalera en espiral.", full: "Estructura propuesta por Watson y Crick (1953). Dos cadenas antiparalelas de nucleótidos unidas por puentes de hidrógeno entre bases complementarias. Un giro completo cada 10 pb (~3,4 nm)." },
      { name: "Nucleótido", emoji: "🔩", color: "#8b5cf6", simple: "Es la 'pieza' básica del ADN: una base, un azúcar y un fosfato.", full: "Monómero del ADN formado por: desoxirribosa (azúcar pentosa), grupo fosfato y una base nitrogenada (A, T, G o C). Se unen por enlaces fosfodiéster 3'-5' formando la columna del ADN." },
      { name: "Adenina (A)", emoji: "🔴", color: "#ef4444", simple: "Una de las 4 letras del ADN. Siempre se une con la Timina (T).", full: "Base púrica (doble anillo). Se empareja con Timina mediante 2 puentes de hidrógeno (A=T). En el ARN se empareja con Uracilo (U). Junto a la ribosa y fosfatos forma el ATP, moneda energética celular." },
      { name: "Guanina (G)", emoji: "🟡", color: "#eab308", simple: "Otra letra del ADN. Siempre se une con la Citosina (C).", full: "Base púrica (doble anillo). Se empareja con Citosina mediante 3 puentes de hidrógeno (G≡C). El par G-C es más estable que A-T por tener un puente de hidrógeno adicional." },
      { name: "Timina (T)", emoji: "🔵", color: "#60a5fa", simple: "Se empareja con la Adenina. Es exclusiva del ADN (no del ARN).", full: "Base pirimídica (anillo simple). Exclusiva del ADN; en el ARN es reemplazada por Uracilo. Se une a Adenina con 2 puentes de hidrógeno. Derivada de la uridina por metilación." },
      { name: "Citosina (C)", emoji: "🟢", color: "#22c55e", simple: "Se empareja con la Guanina. Es una de las 4 bases del ADN.", full: "Base pirimídica (anillo simple). Se une a Guanina con 3 puentes de hidrógeno. Puede sufrir deaminación espontánea a Uracilo (mutación frecuente). Presente tanto en ADN como en ARN." },
      { name: "Histona", emoji: "🎀", color: "#f472b6", simple: "Proteína que envuelve el ADN para que quepa comprimido en la célula.", full: "Proteínas básicas ricas en lisina y arginina. El ADN se enrolla dos veces alrededor de un octámero de histonas (H2A, H2B, H3, H4) formando el nucleosoma. La modificación de histonas regula la expresión génica (epigenética)." },
      { name: "Cromosoma", emoji: "🧵", color: "#a855f7", simple: "Es el ADN muy compactado que se ve durante la división celular.", full: "Estructura de ADN superenrollado con proteínas. El ser humano tiene 46 cromosomas (23 pares) en células somáticas. Cada cromosoma tiene centrómetro, telómeros y regiones específicas (genes y secuencias no codificantes)." },
    ],
  },
  {
    slug: "sistema-nervioso",
    uid: "03a5173f3d2e46958b6f8be81b1c88be",
    title: "Sistema Nervioso",
    subtitle: "🧠 Neurociencia",
    accent: "#a78bfa",
    intro: "Explorá una neurona real en 3D. Tocá los puntos ⓘ en el modelo o las estructuras de abajo.",
    structures: [
      { name: "Dendritas", emoji: "🌿", color: "#22c55e", simple: "Son las 'antenas' de la neurona que reciben señales de otras neuronas.", full: "Prolongaciones ramificadas que aumentan la superficie receptora. Contienen receptores para neurotransmisores. La densidad de espinas dendríticas (sitios sinápticos) se modifica con el aprendizaje (plasticidad sináptica)." },
      { name: "Soma (cuerpo celular)", emoji: "⚪", color: "#94a3b8", simple: "El cuerpo principal de la neurona donde está el núcleo.", full: "Contiene el núcleo, organelas y la maquinaria de síntesis proteica. Integra todas las señales recibidas en dendritas y decide si generar o no un potencial de acción (zona gatillo en el cono axónico)." },
      { name: "Axón", emoji: "➡️", color: "#3b82f6", simple: "El 'cable' largo que lleva la señal eléctrica hacia otras neuronas.", full: "Prolongación única (puede medir hasta 1 metro). Conduce el potencial de acción desde el cono axónico hasta los terminales. La dirección de conducción es siempre del soma hacia los terminales (ortodrómica)." },
      { name: "Vaina de Mielina", emoji: "⚡", color: "#f59e0b", simple: "Envoltura grasa que acelera la transmisión de señales eléctricas.", full: "Producida por células de Schwann (SNP) u oligodendrocitos (SNC). Aumenta la resistencia de la membrana axónica y reduce la capacitancia. Permite conducción saltatoria entre nódulos de Ranvier (hasta 120 m/s vs 0,5 m/s sin mielina)." },
      { name: "Nódulos de Ranvier", emoji: "🔘", color: "#06b6d4", simple: "Son pequeños 'saltos' en la mielina donde la señal se regenera.", full: "Espacios entre segmentos de mielina con alta densidad de canales de Na⁺ voltaje-dependientes. El potencial de acción 'salta' de nódulo en nódulo (conducción saltatoria), aumentando la velocidad y ahorrando energía." },
      { name: "Terminal Axónico", emoji: "🔵", color: "#8b5cf6", simple: "El extremo del axón que libera los mensajeros químicos (neurotransmisores).", full: "Botón sináptico: contiene vesículas con neurotransmisores. Al llegar el PA, canales de Ca²⁺ se abren, el Ca²⁺ dispara la exocitosis de vesículas y los neurotransmisores difunden hacia la hendidura sináptica." },
      { name: "Sinapsis", emoji: "💫", color: "#f43f5e", simple: "Es la conexión entre dos neuronas donde se comunican.", full: "Unión funcional entre neurona presináptica y postsináptica (o célula efectora). La hendidura sináptica mide ~20-40 nm. Los neurotransmisores difunden y se unen a receptores postsinápticos generando PPSE (excitatorios) o PPSI (inhibitorios)." },
      { name: "Neurotransmisor", emoji: "💊", color: "#10b981", simple: "Son los 'mensajes químicos' que las neuronas usan para comunicarse.", full: "Moléculas como glutamato (excitatorio), GABA (inhibitorio), dopamina, serotonina, acetilcolina. Se sintetizan en el soma, se empaquetan en vesículas y se liberan por exocitosis. Su recaptación o degradación termina la señal." },
      { name: "Célula Glial", emoji: "🛡️", color: "#64748b", simple: "Las células de soporte que protegen y alimentan a las neuronas.", full: "Representan el 90% de las células cerebrales. Tipos: astrocitos (soporte metabólico, barrera hematoencefálica), oligodendrocitos (mielina en SNC), microglía (inmunidad), células de Schwann (mielina en SNP)." },
    ],
  },
  {
    slug: "planta",
    uid: "0640c7a14f41400fbdac382c7de1d776",
    title: "Célula Vegetal",
    subtitle: "🌿 Botánica celular",
    accent: "#34d399",
    intro: "Explorá la célula vegetal y sus diferencias con la animal. Tocá los puntos ⓘ o las estructuras de abajo.",
    structures: [
      { name: "Pared Celular", emoji: "🧱", color: "#92400e", simple: "La capa rígida que rodea la célula vegetal y le da forma.", full: "Compuesta principalmente por celulosa (polímero de glucosa). Capa primaria (flexible, en células en crecimiento) y secundaria (lignificada, en células maduras). Da rigidez mecánica y protección. Las plantas la tienen; los animales, no." },
      { name: "Cloroplasto", emoji: "🟢", color: "#16a34a", simple: "Donde ocurre la fotosíntesis: convierte la luz solar en azúcar.", full: "Orgánulo de doble membrana con tilacoides apilados (grana) y estroma. La fase luminosa ocurre en tilacoides (fotosistemas I y II); el Ciclo de Calvin en el estroma. Contiene ADN propio (endosimbiosis con cianobacteria ancestral)." },
      { name: "Vacuola Central", emoji: "💧", color: "#0284c7", simple: "Un gran depósito de agua que mantiene firme a la célula.", full: "Puede ocupar hasta el 90% del volumen celular. Almacena agua, azúcares, iones, pigmentos (antocianinas) y toxinas. La presión de turgencia que genera contra la pared celular mantiene la firmeza de los tejidos. Su pérdida causa la marchitez." },
      { name: "Plasmodesmos", emoji: "🔗", color: "#f59e0b", simple: "Pequeños canales que conectan células vecinas y les permiten comunicarse.", full: "Canales citoplasmáticos que atraviesan la pared celular. Permiten el transporte simplástico de agua, iones, azúcares y señales entre células. Su diámetro (~30-60 nm) puede regularse. Fundamentales en el floema." },
      { name: "Amiloplasto", emoji: "⬜", color: "#d1d5db", simple: "Almacena el almidón (azúcar de reserva) que fabrica la planta.", full: "Tipo de plastidio no pigmentado. Sintetiza y almacena gránulos de almidón (amilosa + amilopectina). Abundantes en tubérculos (papa), semillas y raíces. En células de la raíz también detectan la gravedad (estatocitos)." },
      { name: "Núcleo", emoji: "🔵", color: "#6366f1", simple: "Guarda el ADN con las instrucciones para construir y controlar la planta.", full: "Similar al de células animales pero frecuentemente poliploide en plantas (diploides, tetraploides, etc.). Contiene múltiples cromosomas; los cereales pueden tener muchos más que los humanos (trigo: 42 cromosomas)." },
      { name: "Mitocondria", emoji: "🟠", color: "#f97316", simple: "Produce la energía ATP que la célula necesita para vivir y crecer.", full: "Presente también en células vegetales (además del cloroplasto). Realiza la respiración celular aeróbica. En plantas la relación entre fotosíntesis (cloroplasto) y respiración (mitocondria) determina el balance energético." },
      { name: "Retículo Endoplasmático", emoji: "🟣", color: "#9333ea", simple: "Red de transporte de proteínas y lípidos dentro de la célula.", full: "Sistema de membranas que conecta el núcleo con la periferia celular. El RER sintetiza proteínas de secreción (muchos para la pared celular). El REL produce los lípidos de membrana y metaboliza compuestos secundarios." },
      { name: "Membrana Plasmática", emoji: "🫧", color: "#14b8a6", simple: "La membrana que controla lo que entra y sale de la célula.", full: "Debajo de la pared celular. Regula la osmosis, el transporte de iones y nutrientes. Contiene canales de agua (acuaporinas) y transportadores específicos. Participa en la señalización hormonal (auxinas, citoquininas)." },
      { name: "Aparato de Golgi", emoji: "🟡", color: "#ca8a04", simple: "Empaqueta proteínas y fabrica materiales para la pared celular.", full: "En células vegetales es especialmente activo en la síntesis y secreción de polisacáridos para la pared celular (pectinas, hemicelulosas). Las vesículas de Golgi participan en la formación del fragmoplasto durante la citocinesis." },
      { name: "Ribosoma", emoji: "🟤", color: "#78350f", simple: "Fabrica las proteínas que la célula necesita para crecer y funcionar.", full: "Idénticos en función a los animales (ribosomas 80S en citoplasma). Además, los cloroplastos y mitocondrias tienen sus propios ribosomas 70S (de tipo procariota), evidencia de su origen endosimbiótico." },
    ],
  },
  {
    slug: "cuerpo-humano",
    uid: "035316622877438cb62de673b8f19217",
    title: "Cuerpo Humano",
    subtitle: "🫀 Anatomía Humana",
    accent: "#f87171",
    intro: "Explorá el cuerpo humano completo en 3D. Tocá los puntos ⓘ en el modelo o los sistemas de abajo.",
    structures: [
      { name: "Sistema Circulatorio", emoji: "🫀", color: "#ef4444", simple: "El corazón y los vasos sanguíneos llevan sangre y oxígeno a todo el cuerpo.", full: "Corazón + ~100.000 km de vasos (arterias, venas, capilares). Circulación mayor (corazón → cuerpo) y menor (corazón → pulmones). Bombea ~5 L/min en reposo, hasta 25 L/min en ejercicio intenso." },
      { name: "Sistema Respiratorio", emoji: "🫁", color: "#38bdf8", simple: "Los pulmones toman oxígeno del aire y eliminan el dióxido de carbono.", full: "Vías aéreas (nariz, laringe, tráquea, bronquios) + pulmones con ~300M alvéolos. Superficie de intercambio ~70 m². Respiramos ~20.000 veces/día. El diafragma es el principal músculo inspiratorio." },
      { name: "Sistema Digestivo", emoji: "🍽️", color: "#f97316", simple: "Transforma los alimentos en nutrientes que el cuerpo puede usar.", full: "Tubo digestivo de ~9 m (boca → ano) + glándulas accesorias (hígado, páncreas, vesícula). Divide los alimentos en nutrientes absorbibles: carbohidratos → glucosa, proteínas → aminoácidos, grasas → ácidos grasos." },
      { name: "Sistema Nervioso", emoji: "⚡", color: "#a855f7", simple: "El cerebro y los nervios controlan todo el cuerpo y procesan los sentidos.", full: "SNC (cerebro + cerebelo + tronco encefálico + médula espinal) + SNP (nervios craneales y espinales). ~86.000 millones de neuronas. Procesa información sensorial, coordina movimiento y regula funciones autónomas." },
      { name: "Sistema Esquelético", emoji: "🦴", color: "#94a3b8", simple: "Los 206 huesos dan estructura, protegen órganos y permiten el movimiento.", full: "206 huesos en adultos (305 en recién nacidos, se fusionan). Función: sostén mecánico, protección (cráneo → cerebro, costillas → pulmones/corazón), hematopoyesis (médula roja), reserva de calcio y fósforo." },
      { name: "Sistema Muscular", emoji: "💪", color: "#f59e0b", simple: "Los músculos permiten el movimiento del cuerpo y mantienen la postura.", full: "~600 músculos esqueléticos (~40% del peso corporal). Mecanismo: deslizamiento actina-miosina dependiente de ATP y Ca²⁺. Tipos: estriado esquelético (voluntario), liso (vísceras, involuntario) y cardíaco." },
      { name: "Sistema Endócrino", emoji: "🔬", color: "#10b981", simple: "Las glándulas producen hormonas que regulan el crecimiento y el metabolismo.", full: "Hipotálamo, hipófisis, tiroides, paratiroides, suprarrenales, páncreas endócrino, gónadas. Regula metabolismo, crecimiento, reproducción y respuesta al estrés. Las hormonas actúan en órganos diana a través de receptores específicos." },
      { name: "Sistema Inmune", emoji: "🛡️", color: "#22c55e", simple: "Protege al cuerpo de bacterias, virus y enfermedades.", full: "Inmunidad innata (barreras físicas, macrófagos, NK) y adaptativa (linfocitos T y B, anticuerpos). Los linfocitos B producen anticuerpos específicos; los T CD4⁺ coordinan la respuesta; los T CD8⁺ destruyen células infectadas." },
      { name: "Sistema Urinario", emoji: "💧", color: "#0ea5e9", simple: "Los riñones filtran la sangre y eliminan los desechos por la orina.", full: "Riñones (~1M nefronas cada uno) filtran 180 L de plasma/día → 1,5 L de orina. Regulan pH, concentración de electrolitos y presión arterial (sistema renina-angiotensina-aldosterona). Eliminan urea, creatinina y fármacos." },
      { name: "Sistema Reproductor", emoji: "🧬", color: "#f472b6", simple: "Permite la reproducción y la continuidad de la vida humana.", full: "Masculino: testículos (producen espermatozoides y testosterona), epidídimo, conductos deferentes, próstata. Femenino: ovarios (óvulos y estrógenos/progesterona), trompas, útero. La fertilización da origen a un zigoto diploide." },
      { name: "Piel (sistema tegumentario)", emoji: "🫂", color: "#a16207", simple: "La piel es el órgano más grande: protege, regula la temperatura y nos permite sentir.", full: "Órgano más grande (~2 m²). Capas: epidermis (queratina, melanocitos, células de Langerhans), dermis (colágeno, vasos, nervios) e hipodermis (grasa). Regula temperatura por sudoración y vasoconstricción/vasodilatación." },
    ],
  },
  {
    slug: "corazon",
    uid: "10472481071e4375b8233289c277d411",
    title: "Corazón Humano",
    subtitle: "🫀 Sistema Circulatorio",
    accent: "#f87171",
    intro: "Explorá la anatomía externa del corazón humano en 3D. Tocá los puntos ⓘ en el modelo o las estructuras de abajo.",
    structures: [
      { name: "Ventrículo Izquierdo", emoji: "🔴", color: "#ef4444", simple: "Bombea sangre con oxígeno a todo el cuerpo con mucha fuerza.", full: "Cámara de pared más gruesa (~12 mm) que genera presión sistólica (~120 mmHg). Expulsa sangre oxigenada a la aorta. Su hipertrofia indica hipertensión arterial crónica." },
      { name: "Ventrículo Derecho", emoji: "🩸", color: "#f97316", simple: "Envía sangre sin oxígeno a los pulmones para que se oxigene.", full: "Pared más delgada que el izquierdo (~3-4 mm). Genera presión pulmonar (~25 mmHg). Bombea sangre desoxigenada a los pulmones a través de la arteria pulmonar para el intercambio gaseoso." },
      { name: "Aurícula Izquierda", emoji: "🫀", color: "#ec4899", simple: "Recibe la sangre con oxígeno que viene de los pulmones.", full: "Recibe la sangre oxigenada de las 4 venas pulmonares. Pasa la sangre al ventrículo izquierdo a través de la válvula mitral (bicúspide). Sitio frecuente de fibrilación auricular." },
      { name: "Aurícula Derecha", emoji: "🩷", color: "#fb7185", simple: "Recibe la sangre usada del cuerpo antes de enviarla a los pulmones.", full: "Recibe sangre desoxigenada de la vena cava superior e inferior y el seno coronario. Comunica con el ventrículo derecho por la válvula tricúspide. Contiene el nódulo sinusal (marcapasos natural)." },
      { name: "Aorta", emoji: "🔴", color: "#dc2626", simple: "Es la arteria más grande: lleva sangre con oxígeno a todo el cuerpo.", full: "Arteria más grande del cuerpo (diámetro ~2,5 cm). Sale del ventrículo izquierdo. Tiene arco aórtico con ramas hacia cabeza y brazos, luego desciende dando ramas a órganos torácicos y abdominales." },
      { name: "Arteria Pulmonar", emoji: "🟣", color: "#a855f7", simple: "Lleva sangre sin oxígeno desde el corazón hasta los pulmones.", full: "Única arteria que transporta sangre desoxigenada. Sale del ventrículo derecho y se divide en arteria pulmonar derecha e izquierda. Es el inicio de la circulación menor o pulmonar." },
      { name: "Válvula Aórtica", emoji: "🔑", color: "#f59e0b", simple: "Es una 'puerta' que evita que la sangre vuelva al corazón después de salir.", full: "Válvula semilunar con 3 valvas (cúspides). Separa el ventrículo izquierdo de la aorta. Se abre en sístole y cierra en diástole. La estenosis aórtica es una de las valvulopatías más frecuentes." },
      { name: "Arterias Coronarias", emoji: "💛", color: "#eab308", simple: "Son los vasos que alimentan al propio corazón con sangre y oxígeno.", full: "Coronaria izquierda (descendente anterior y circunfleja) y derecha. Surgen de la raíz aórtica y riegan el miocardio. Su obstrucción causa infarto de miocardio. Objeto de bypass coronario y stents." },
      { name: "Pericardio", emoji: "🛡️", color: "#64748b", simple: "Es la bolsa protectora que envuelve y protege al corazón.", full: "Saco fibroso de doble capa (parietal y visceral) con líquido pericárdico (~20-50 mL) que reduce la fricción. Fija el corazón al mediastino. La pericarditis causa dolor torácico intenso." },
    ],
  },
  {
    slug: "cerebro",
    uid: "28c8971e11334e8b97a2a0d6235992e8",
    title: "Cerebro Humano",
    subtitle: "🧠 Sistema Nervioso Central",
    accent: "#c084fc",
    intro: "Explorá la anatomía del cerebro humano en 3D con sus partes etiquetadas. Tocá los puntos ⓘ o las estructuras de abajo.",
    structures: [
      { name: "Corteza Cerebral", emoji: "🧠", color: "#a855f7", simple: "Es la capa exterior del cerebro donde se procesa el pensamiento, la memoria y los sentidos.", full: "Capa de sustancia gris (~2-4 mm) con ~16.000 millones de neuronas. Organizada en lóbulos: frontal (razonamiento, movimiento), parietal (sensación), temporal (audición, memoria) y occipital (visión). Tiene circunvoluciones que aumentan la superficie." },
      { name: "Lóbulo Frontal", emoji: "💭", color: "#8b5cf6", simple: "Controla el movimiento, las decisiones, el lenguaje y la personalidad.", full: "Mayor lóbulo cerebral. Contiene la corteza motora primaria (control voluntario del movimiento), el área de Broca (producción del lenguaje) y la corteza prefrontal (razonamiento, planificación, control de impulsos)." },
      { name: "Lóbulo Parietal", emoji: "👋", color: "#7c3aed", simple: "Procesa las sensaciones del cuerpo: tacto, temperatura y dolor.", full: "Contiene la corteza somatosensorial primaria (procesa tacto, propiocepción, temperatura y dolor). Integra información sensorial para la percepción espacial. El área de Wernicke (comprensión del lenguaje) está en el límite parieto-temporal." },
      { name: "Cerebelo", emoji: "⚖️", color: "#6d28d9", simple: "Coordina el equilibrio y los movimientos precisos del cuerpo.", full: "Situado en la fosa craneal posterior. Contiene más neuronas que todo el resto del cerebro. Coordina la precisión, el tono muscular y el equilibrio. Recibe info del córtex motor y la integra con señales propioceptivas y vestibulares." },
      { name: "Tronco Encefálico", emoji: "🔌", color: "#5b21b6", simple: "Conecta el cerebro con la médula espinal y controla funciones vitales como respirar.", full: "Formado por mesencéfalo, protuberancia y bulbo raquídeo. Controla funciones autónomas vitales: frecuencia cardíaca, respiración, presión arterial. Contiene los núcleos de los pares craneales III-XII." },
      { name: "Tálamo", emoji: "📡", color: "#4c1d95", simple: "Es el 'relé' del cerebro: filtra y distribuye toda la información sensorial.", full: "Estructura diencefálica de doble núcleo. Es la puerta de entrada a la corteza cerebral para casi toda la información sensorial (excepto olfativa). Regula la conciencia, el sueño y la alerta. Sus núcleos se asocian a funciones específicas corticales." },
      { name: "Hipocampo", emoji: "🐎", color: "#7e22ce", simple: "Ayuda a guardar nuevos recuerdos y orientarse en el espacio.", full: "Estructura del sistema límbico (lóbulo temporal medial). Esencial para la formación de memoria declarativa (episódica y semántica) y la navegación espacial. En Alzheimer, es una de las primeras regiones afectadas por la neurodegeneración." },
      { name: "Cuerpo Calloso", emoji: "🔗", color: "#9333ea", simple: "Es el puente de fibras que conecta el hemisferio izquierdo con el derecho.", full: "Mayor comisura interhemisférica: ~200-250 millones de axones mielinizados. Permite la comunicación y coordinación entre los dos hemisferios. Su sección (callosotomía) se realiza en epilepsia refractaria severa." },
    ],
  },
  {
    slug: "pulmones",
    uid: "ce09f4099a68467880f46e61eb9a3531",
    title: "Sistema Respiratorio",
    subtitle: "💨 Pulmones y Vías Aéreas",
    accent: "#38bdf8",
    intro: "Explorá los pulmones y las vías respiratorias en 3D. Tocá los puntos ⓘ en el modelo o las estructuras de abajo.",
    structures: [
      { name: "Pulmón Derecho", emoji: "🫁", color: "#0ea5e9", simple: "El pulmón más grande, dividido en 3 partes (lóbulos). Toma el oxígeno del aire.", full: "Mayor que el izquierdo. Tiene 3 lóbulos (superior, medio e inferior) separados por las cisuras horizontal y oblicua. Contiene ~300 millones de alvéolos. Ocupa la mayor parte de la cavidad torácica derecha." },
      { name: "Pulmón Izquierdo", emoji: "🫁", color: "#38bdf8", simple: "El pulmón más pequeño, con 2 partes. Está al lado del corazón.", full: "Tiene 2 lóbulos (superior e inferior) separados por la cisura oblicua. Es más pequeño por la presencia del corazón (escotadura cardíaca). Contiene la língula, homóloga del lóbulo medio derecho." },
      { name: "Tráquea", emoji: "🎺", color: "#7dd3fc", simple: "Es el tubo principal por donde el aire entra y llega a los pulmones.", full: "Conducto cartilaginoso (18-20 anillos en C de cartílago hialino) de ~12 cm de longitud. Se bifurca en la carina en los dos bronquios principales. Revestida por epitelio ciliado pseudoestratificado que atrapa partículas." },
      { name: "Bronquios Principales", emoji: "🌿", color: "#22d3ee", simple: "Son las ramas del tubo principal que llevan el aire a cada pulmón.", full: "Bronquio derecho es más corto, ancho y vertical (mayor riesgo de aspiración). Cada bronquio se divide en bronquios lobares, segmentarios y luego en bronquiolos. El árbol bronquial tiene ~23 generaciones de ramificación." },
      { name: "Alvéolos", emoji: "🫧", color: "#06b6d4", simple: "Son pequeñas bolsitas donde el oxígeno pasa a la sangre y sale el dióxido de carbono.", full: "Unidades funcionales del intercambio gaseoso. Paredes formadas por neumocitos tipo I (intercambio) y tipo II (producen surfactante que evita el colapso). La membrana alvéolo-capilar tiene ~0,2 µm de grosor para difusión eficiente de O₂ y CO₂." },
      { name: "Pleura", emoji: "🛡️", color: "#0891b2", simple: "Es la doble envoltura que protege los pulmones y permite que se expandan.", full: "Membrana serosa de doble capa: visceral (adherida al pulmón) y parietal (adherida a la pared torácica). La cavidad pleural contiene ~10-20 mL de líquido lubricante. El neumotórax (entrada de aire) colapsa el pulmón." },
      { name: "Diafragma", emoji: "💪", color: "#0284c7", simple: "Es el músculo principal de la respiración: al bajar, hace entrar aire a los pulmones.", full: "Principal músculo inspiratorio. Al contraerse se aplana, aumentando el volumen torácico y generando presión negativa que infla los pulmones. Inervado por el nervio frénico (C3-C5). Separa cavidad torácica de la abdominal." },
      { name: "Capilares Pulmonares", emoji: "🩸", color: "#ef4444", simple: "Son los vasos sanguíneos tiny que rodean cada bolsita de aire para intercambiar gases.", full: "Red capilar densa (~280.000 millones de capilares) que rodea los alvéolos. Superficie total de intercambio ~70 m². La hemoglobina transporta O₂ y CO₂. La hematosis (intercambio gaseoso) ocurre en ~0,25 segundos." },
    ],
  },
  {
    slug: "digestivo",
    uid: "2d3771dd6b8940ffa2312bd97aca6fc3",
    title: "Sistema Digestivo",
    subtitle: "🍽️ Aparato Digestivo",
    accent: "#fb923c",
    intro: "Explorá el sistema digestivo humano en 3D. Tocá los puntos ⓘ en el modelo o las estructuras de abajo.",
    structures: [
      { name: "Boca y Esófago", emoji: "👄", color: "#f97316", simple: "La boca tritura los alimentos y el esófago los lleva al estómago.", full: "Boca: masticación mecánica y digestión química inicial (amilasa salival). Deglución involucra 30+ músculos. Esófago: tubo muscular de ~25 cm con peristalsis para transportar el bolo alimenticio. Esfínter esofágico inferior previene el reflujo." },
      { name: "Estómago", emoji: "💛", color: "#eab308", simple: "Mezcla los alimentos con jugos ácidos para descomponerlos.", full: "Órgano muscular en forma de J. Produce HCl (pH 1,5-2) y pepsina para la digestión proteica. Las células parietales secretan ácido; las principales, pepsinógeno. La mucosa produce mucus protector. Vacía su contenido (quimo) en 2-4 horas." },
      { name: "Intestino Delgado", emoji: "🌀", color: "#22c55e", simple: "Es el tubo más largo: absorbe los nutrientes de los alimentos.", full: "Mide ~6-7 m. Dividido en duodeno (digestión con enzimas pancreáticas y bilis), yeyuno (absorción principal) e íleon. Tiene vellosidades y microvellosidades que aumentan la superficie absortiva a ~250 m². Absorbe el 95% de los nutrientes." },
      { name: "Intestino Grueso", emoji: "🟤", color: "#92400e", simple: "Absorbe agua y forma las heces con lo que no se digirió.", full: "Mide ~1,5 m. Incluye ciego, colon (ascendente, transverso, descendente, sigmoide) y recto. Absorbe agua y electrolitos. Contiene la microbiota intestinal (~100 billones de bacterias). Fermenta fibra no digerible produciendo ácidos grasos de cadena corta." },
      { name: "Hígado", emoji: "🟫", color: "#b45309", simple: "Produce la bilis, filtra la sangre y procesa los nutrientes absorbidos.", full: "Mayor glándula del cuerpo (~1,5 kg). Produce bilis para emulsionar grasas. Metaboliza glucosa (glucogénesis/glucólisis), sintetiza proteínas plasmáticas (albúmina, factores de coagulación) y detoxifica fármacos y toxinas. Recibe sangre portal del intestino." },
      { name: "Vesícula Biliar", emoji: "💚", color: "#16a34a", simple: "Almacena la bilis del hígado y la libera cuando comés grasas.", full: "Saco de ~8 cm que concentra y almacena bilis (hasta 50 mL). Al ingerir grasas, la colecistoquinina (CCK) estimula su contracción y libera bilis por el conducto colédoco al duodeno. Los cálculos biliares son frecuentes (10-20% de adultos)." },
      { name: "Páncreas", emoji: "🩶", color: "#64748b", simple: "Produce jugos digestivos y la insulina que regula el azúcar en sangre.", full: "Glándula mixta: exocrina (jugo pancreático con lipasas, proteasas, amilasa para digestión en duodeno) y endocrina (islotes de Langerhans — células β producen insulina, células α glucagón). La diabetes tipo 1 destruye las células β." },
      { name: "Apéndice", emoji: "📍", color: "#f43f5e", simple: "Es una pequeña extensión del intestino grueso. Puede inflamarse (apendicitis).", full: "Divertículo ciego de ~8 cm unido al ciego. Tiene tejido linfoide (MALT) que forma parte del sistema inmune intestinal. Puede albergar bacterias beneficiosas. Su inflamación (apendicitis) requiere extirpación quirúrgica urgente." },
    ],
  },
  // ── Sistema Óseo ──────────────────────────────────────────
  {
    slug: "oseo",
    uid: "911b9df7e7834175b69b4840ea15e054",
    title: "Sistema Óseo",
    subtitle: "🦴 Esqueleto Humano",
    accent: "#94a3b8",
    intro: "Explorá el esqueleto humano en 3D: 206 huesos que sostienen, protegen y permiten el movimiento.",
    structures: [
      { name: "Cráneo", emoji: "💀", color: "#e2e8f0", simple: "Es la caja dura que protege al cerebro y forma la cara.", full: "Formado por 22 huesos fusionados (8 craneales + 14 faciales). Las suturas son articulaciones fijas. La base craneal tiene orificios (forámenes) para nervios craneales y vasos sanguíneos." },
      { name: "Columna Vertebral", emoji: "🔗", color: "#cbd5e1", simple: "Es la columna de huesos que sostiene el cuerpo y protege la médula espinal.", full: "33 vértebras en 5 regiones: cervical (7), torácica (12), lumbar (5), sacra (5 fusionadas) y coccígea (4 fusionadas). Los discos intervertebrales amortiguan impactos." },
      { name: "Costillas y Esternón", emoji: "🛡️", color: "#94a3b8", simple: "Las costillas forman la caja que protege el corazón y los pulmones.", full: "12 pares de costillas articuladas con vértebras torácicas. Las 7 primeras son 'verdaderas' (unidas al esternón directamente). La caja torácica permite movimientos respiratorios." },
      { name: "Húmero", emoji: "💪", color: "#a8b4c0", simple: "Es el hueso del brazo que conecta el hombro con el codo.", full: "Hueso largo del brazo. La cabeza humeral se articula con la escápula (articulación glenohumeral). El epicóndilo y tróclea se articulan con radio y cúbito en el codo." },
      { name: "Pelvis", emoji: "🦵", color: "#7c8fa0", simple: "Es el anillo de huesos que une la columna con las piernas y protege los órganos internos.", full: "Formada por 2 huesos coxales (ilion, isquion, pubis fusionados) + sacro + cóccix. Transmite el peso del tronco a los miembros inferiores." },
      { name: "Fémur", emoji: "🦴", color: "#64748b", simple: "Es el hueso más largo del cuerpo, está en el muslo.", full: "Hueso más largo y resistente del esqueleto (~50 cm). La cabeza femoral forma la articulación de la cadera (coxofemoral). Los cóndilos femorales se articulan con la tibia en la rodilla." },
      { name: "Tibia y Peroné", emoji: "🦶", color: "#475569", simple: "Son los dos huesos de la pierna que conectan la rodilla con el tobillo.", full: "Tibia: hueso principal que soporta el peso. Peroné: más delgado, lateral. La tibia se articula con el fémur (articulación de la rodilla con meniscos y ligamentos cruzados)." },
      { name: "Articulación", emoji: "⚙️", color: "#b0bec5", simple: "Es la unión entre dos huesos que permite el movimiento.", full: "Tipos: sinartrosis (fijas, como suturas craneales), anfiartrosis (semimóviles) y diartrosis (sinoviales, las más móviles). Las diartrosis tienen cartílago articular, líquido sinovial y cápsula articular." },
      { name: "Cartílago", emoji: "🌊", color: "#93c5fd", simple: "Es un tejido elástico que cubre los extremos de los huesos y amortigua los golpes.", full: "Tejido conectivo avascular. Tipos: hialino (articulaciones), elástico (oreja) y fibrocartílago (meniscos, discos intervertebrales). Los condrocitos producen la matriz de colágeno y proteoglucanos." },
      { name: "Periostio", emoji: "🔵", color: "#6366f1", simple: "Es la membrana que recubre los huesos y contiene células que los hacen crecer.", full: "Membrana fibrosa que cubre los huesos largos (excepto superficies articulares). Rica en osteoblastos y osteoclastos. Esencial para la reparación ósea tras fracturas." },
    ],
  },
  // ── Sistema Muscular ──────────────────────────────────────
  {
    slug: "muscular",
    uid: "991eb96938be4d0d8fadee241a1063d3",
    title: "Sistema Muscular",
    subtitle: "💪 Músculos del Cuerpo",
    accent: "#f87171",
    intro: "Más de 600 músculos dan movimiento, postura y calor al cuerpo. Explorá los principales grupos musculares en 3D.",
    structures: [
      { name: "Músculo Esquelético", emoji: "💪", color: "#ef4444", simple: "Son los músculos que movemos voluntariamente, como el bíceps.", full: "Tejido muscular estriado bajo control voluntario. Formado por fascículos de fibras musculares con miofibrillas. Contrae por el mecanismo de deslizamiento de filamentos (actina-miosina)." },
      { name: "Músculo Cardíaco", emoji: "🫀", color: "#dc2626", simple: "Es el músculo del corazón: trabaja solo, sin parar, toda la vida.", full: "Tejido estriado involuntario exclusivo del corazón. Las células (cardiomiocitos) están interconectadas por discos intercalares. Se contrae rítmicamente gracias al nódulo sinusal." },
      { name: "Músculo Liso", emoji: "🌀", color: "#f97316", simple: "Son los músculos de los órganos internos: trabajan solos sin que los controlemos.", full: "Tejido muscular no estriado, involuntario. Presente en paredes de órganos huecos (intestinos, vasos sanguíneos, vejiga). Controlado por el sistema nervioso autónomo y hormonas." },
      { name: "Sarcómero", emoji: "🔬", color: "#fbbf24", simple: "Es la unidad más pequeña del músculo que produce la contracción.", full: "Unidad estructural y funcional del músculo estriado. Delimitado por dos discos Z. Contiene filamentos gruesos de miosina (banda A) y delgados de actina (banda I). Durante la contracción, los filamentos se deslizan entre sí." },
      { name: "Actina y Miosina", emoji: "🔗", color: "#fb923c", simple: "Son las proteínas que se enganchan entre sí para hacer que el músculo se acorte.", full: "Actina (filamento delgado): proteína globular que forma doble hélice. Miosina (filamento grueso): tiene 'cabezas' que se unen a actina y usan ATP para generar fuerza." },
      { name: "Tendón", emoji: "🔴", color: "#b91c1c", simple: "Es el cordón resistente que une el músculo con el hueso.", full: "Tejido conectivo denso formado por fibras de colágeno tipo I dispuestas en paralelo. Transmite la fuerza generada por el músculo al hueso. El tendón de Aquiles es el más grueso del cuerpo." },
      { name: "Unión Neuromuscular", emoji: "⚡", color: "#f59e0b", simple: "Es el lugar donde el nervio le da la orden al músculo para contraerse.", full: "Sinapsis entre la motoneurona alfa y la fibra muscular. El potencial de acción libera acetilcolina que activa receptores nicotínicos, generando un potencial de acción muscular que libera Ca²⁺." },
      { name: "Deltoides", emoji: "🔺", color: "#e11d48", simple: "Es el músculo del hombro que levanta el brazo hacia el costado.", full: "Músculo triangular que cubre la articulación glenohumeral. Permite abducción, flexión y extensión del hombro. Inervado por el nervio axilar (C5-C6)." },
      { name: "Cuádriceps", emoji: "🦵", color: "#c026d3", simple: "Son los cuatro músculos de la parte delantera del muslo que extienden la rodilla.", full: "Grupo de 4 músculos: recto femoral, vasto lateral, vasto medial y vasto intermedio. Es el músculo más potente del cuerpo. Esencial para caminar, correr y saltar." },
      { name: "Abdominales", emoji: "🟧", color: "#ea580c", simple: "Son los músculos del abdomen que protegen los órganos y doblan el tronco.", full: "Incluyen recto abdominal, oblicuos interno/externo y transverso. Forman la 'pared abdominal'. Flexionan el tronco y ayudan en la espiración forzada." },
    ],
  },
  // ── Sistema Excretor ──────────────────────────────────────
  {
    slug: "excretor",
    uid: "4258252eb7c04e748ab7501eb5f1abb1",
    title: "Sistema Excretor",
    subtitle: "💧 Riñones y Vías Urinarias",
    accent: "#facc15",
    intro: "Los riñones filtran toda la sangre unas 60 veces por día. Explorá el sistema urinario en 3D.",
    structures: [
      { name: "Riñón", emoji: "🫘", color: "#ca8a04", simple: "Es el órgano que limpia la sangre y produce la orina.", full: "Órgano par retroperitoneal con forma de frijol (~12 cm). Cada riñón contiene ~1 millón de nefronas. Filtra ~180 L de plasma/día y produce ~1,5 L de orina." },
      { name: "Corteza Renal", emoji: "🔴", color: "#b45309", simple: "Es la capa exterior del riñón donde se filtra la sangre.", full: "Zona externa del riñón. Contiene los corpúsculos renales (glomérulo + cápsula de Bowman) y la mayoría de los túbulos contorneados." },
      { name: "Médula Renal", emoji: "🟡", color: "#d97706", simple: "Es la parte interna del riñón con los tubos que concentran la orina.", full: "Zona interna formada por pirámides de Malpighi. Contiene las asas de Henle y los túbulos colectores. La ADH controla la reabsorción de agua en los colectores." },
      { name: "Glomérulo", emoji: "🔵", color: "#0284c7", simple: "Es un ovillo de vasos pequeños en el riñón donde la sangre se filtra.", full: "Red de capilares fenestrados dentro de la cápsula de Bowman. La membrana de filtración impide el paso de proteínas grandes. Filtrado: ~125 mL/min (TFG normal)." },
      { name: "Cápsula de Bowman", emoji: "🫧", color: "#38bdf8", simple: "Es la 'taza' que rodea al glomérulo y recoge el líquido filtrado.", full: "Doble pared en forma de copa que rodea al glomérulo. La capa visceral tiene podocitos con procesos filtrantes (pedicelos). El espacio urinario recoge el ultrafiltrado." },
      { name: "Asa de Henle", emoji: "🔄", color: "#a78bfa", simple: "Es un tubo en forma de U que concentra la orina recuperando agua y sales.", full: "Segmento tubular en forma de U que desciende a la médula y regresa. La rama descendente es permeable al agua. La rama ascendente reabsorbe activamente Na⁺, K⁺ y Cl⁻." },
      { name: "Uréter", emoji: "〰️", color: "#f97316", simple: "Es el tubo que lleva la orina desde el riñón hasta la vejiga.", full: "Conducto muscular (~25-30 cm) con 3 capas. Transporta orina por contracciones peristálticas. Tiene zonas de estrechez anatómica en la unión ureteropélvica y ureterovesical." },
      { name: "Vejiga Urinaria", emoji: "🫙", color: "#84cc16", simple: "Es la bolsa que almacena la orina hasta que la eliminamos.", full: "Órgano muscular hueco (músculo detrusor) que almacena 300-500 mL de orina. El reflejo miccional coordina el vaciado. Los esfínteres interno (liso) y externo (estriado) controlan la micción." },
    ],
  },
  // ── Mitosis y Meiosis ─────────────────────────────────────
  {
    slug: "mitosis",
    uid: "df93411c475c4e4eb450f71437b5ad0d",
    title: "Mitosis y Meiosis",
    subtitle: "🔬 División Celular",
    accent: "#818cf8",
    intro: "La mitosis crea copias idénticas de células. La meiosis produce gametos para la reproducción. Explorá las fases en 3D.",
    structures: [
      { name: "Interfase", emoji: "⏸️", color: "#6366f1", simple: "Es la fase de 'preparación' donde la célula crece y copia su ADN antes de dividirse.", full: "Ocupa el 90% del ciclo celular. Se divide en G1 (crecimiento), S (replicación del ADN: contenido pasa de 2n a 4n) y G2 (síntesis de proteínas para la mitosis)." },
      { name: "Profase", emoji: "🌀", color: "#7c3aed", simple: "Los cromosomas se hacen visibles y el núcleo empieza a desarmarse.", full: "Los cromosomas se condensan y se hacen visibles. La envoltura nuclear se desintegra. Los centrosomas migran a polos opuestos. Comienza a formarse el huso mitótico." },
      { name: "Metafase", emoji: "⬜", color: "#4f46e5", simple: "Los cromosomas se alinean en el centro de la célula, como en fila.", full: "Los cromosomas se alinean en la placa metafásica (ecuador). Los cinetocoros se unen a los microtúbulos del huso. El checkpoint de ensamblaje verifica la unión correcta." },
      { name: "Anafase", emoji: "⬆️", color: "#3730a3", simple: "Las cromátidas hermanas se separan y se mueven hacia extremos opuestos.", full: "La cohesina que une cromátidas es degradada. Las cromátidas hermanas son jaladas hacia polos opuestos por el acortamiento de microtúbulos cinetocóricos." },
      { name: "Telofase", emoji: "🟣", color: "#6d28d9", simple: "Se forman dos nuevos núcleos en cada extremo de la célula.", full: "Los cromosomas hijos llegan a los polos y se descondensan. Se reorganiza la envoltura nuclear. El nucléolo reaparece. Comienza simultáneamente la citocinesis." },
      { name: "Citocinesis", emoji: "✂️", color: "#8b5cf6", simple: "Es la división del citoplasma que separa las dos células hijas.", full: "En células animales: el anillo contráctil de actina-miosina forma una constricción hasta separar las células. En células vegetales: la placa celular forma una nueva pared." },
      { name: "Huso Mitótico", emoji: "🕸️", color: "#a78bfa", simple: "Es la estructura de fibras que jala los cromosomas hacia cada extremo de la célula.", full: "Estructura bipolar formada por microtúbulos de tubulina. Tipos: cinetocóricos, polares y astrales. Los centrosomas (MTOC) nuclean los microtúbulos." },
      { name: "Meiosis I y II", emoji: "🧬", color: "#c4b5fd", simple: "La meiosis tiene dos divisiones y produce 4 células con la mitad de los cromosomas.", full: "Meiosis I (reduccional): separa cromosomas homólogos. El crossing-over en profase I genera recombinación genética. Meiosis II (ecuacional): separa cromátidas hermanas. Resultado: 4 células haploides (n)." },
    ],
  },
  // ── Sistema Inmunológico ──────────────────────────────────
  {
    slug: "inmunologico",
    uid: "557451d5e6ca496d8c691e14b42edd93",
    title: "Sistema Inmunológico",
    subtitle: "🛡️ Defensa del Organismo",
    accent: "#ef4444",
    intro: "El sistema inmune defiende al cuerpo de bacterias, virus y células cancerosas. Explorá las células y órganos en 3D.",
    structures: [
      { name: "Linfocito B", emoji: "🔵", color: "#3b82f6", simple: "Es la célula que fabrica anticuerpos para atacar a los gérmenes.", full: "Linfocito de la inmunidad humoral. Al activarse, se diferencia en plasmocitos que secretan anticuerpos específicos. También forma células B de memoria para respuestas secundarias." },
      { name: "Linfocito T Helper", emoji: "🟢", color: "#22c55e", simple: "Es el 'director' del sistema inmune: activa a otras células de defensa.", full: "Linfocito CD4+. Reconoce antígenos presentados por CPAs (MHC-II). Secreta citoquinas (IL-2, IL-4, IFN-γ) que activan linfocitos B, T citotóxicos y macrófagos." },
      { name: "Linfocito T Citotóxico", emoji: "⚔️", color: "#ef4444", simple: "Es la célula 'asesina' que destruye directamente células infectadas o cancerosas.", full: "Linfocito CD8+. Reconoce péptidos antigénicos presentados en MHC-I. Destruye células diana liberando perforina y granzimas que activan la apoptosis." },
      { name: "Macrófago", emoji: "😤", color: "#f97316", simple: "Es una célula grande que 'come' gérmenes, células muertas y restos del cuerpo.", full: "Monocito diferenciado en los tejidos. Realiza fagocitosis de patógenos. Presenta antígenos en MHC-II a linfocitos T. Secreta citoquinas proinflamatorias." },
      { name: "Neutrófilo", emoji: "⚪", color: "#94a3b8", simple: "Es el glóbulo blanco más abundante: el primero en llegar cuando hay una infección.", full: "Leucocito más numeroso (60-70%). Primera línea de defensa en la inflamación aguda. Destruye patógenos por fagocitosis, degranulación y trampas de ADN (NETs)." },
      { name: "Anticuerpo (Inmunoglobulina)", emoji: "🛡️", color: "#a855f7", simple: "Es una proteína en forma de Y que se pega al germen y lo marca para destruir.", full: "Proteína en forma de Y con 2 cadenas pesadas y 2 ligeras. Las regiones variables (Fab) unen antígenos específicos. La región Fc activa el complemento o la fagocitosis." },
      { name: "Célula NK (Natural Killer)", emoji: "⚡", color: "#f59e0b", simple: "Es la célula que mata células infectadas o tumorales sin necesitar que le avisen.", full: "Linfocito de inmunidad innata. No necesita activación previa. Detecta células con MHC-I reducido. Mata por perforina y granzimas." },
      { name: "Timo", emoji: "🫀", color: "#ec4899", simple: "Es el órgano donde los linfocitos T 'aprenden' a distinguir lo propio de lo extraño.", full: "Órgano linfoide primario en el mediastino anterior. Los timocitos maduran bajo influencia de las células epiteliales tímicas por selección positiva y negativa." },
      { name: "Bazo", emoji: "🫘", color: "#64748b", simple: "Es el órgano que filtra la sangre y activa la respuesta inmune en el torrente sanguíneo.", full: "Mayor órgano linfoide secundario. Pulpa roja: filtra eritrocitos viejos. Pulpa blanca: contiene linfocitos T y B. La esplenectomía aumenta el riesgo de infecciones graves." },
    ],
  },
  // ── Sistema Endócrino ─────────────────────────────────────
  {
    slug: "endocrino",
    uid: "b10f70cacb6946da851e5696291398a5",
    title: "Sistema Endócrino",
    subtitle: "⚗️ Glándulas y Hormonas",
    accent: "#fb923c",
    intro: "El sistema endócrino regula el metabolismo, el crecimiento, la reproducción y el estrés mediante hormonas. Explorá las principales glándulas en 3D.",
    structures: [
      { name: "Hipotálamo", emoji: "🧠", color: "#8b5cf6", simple: "Es la parte del cerebro que controla a casi todas las glándulas del cuerpo.", full: "Región diencefálica que conecta el sistema nervioso con el endócrino. Produce hormonas liberadoras e inhibidoras (GnRH, TRH, CRH, GHRH) que regulan la hipófisis." },
      { name: "Hipófisis (Pituitaria)", emoji: "🔵", color: "#3b82f6", simple: "Es la 'glándula maestra': controla a la mayoría de las otras glándulas.", full: "Adenohipófisis (anterior): produce GH, TSH, ACTH, FSH, LH, prolactina. Neurohipófisis (posterior): almacena y libera ADH y oxitocina sintetizadas en el hipotálamo." },
      { name: "Tiroides", emoji: "🦋", color: "#22d3ee", simple: "Es la glándula del cuello que controla la velocidad del metabolismo del cuerpo.", full: "Glándula bilobulada que produce T3 y T4 que aumentan el metabolismo basal y el crecimiento. También produce calcitonina (reduce calcemia)." },
      { name: "Glándulas Suprarrenales", emoji: "🔴", color: "#ef4444", simple: "Son dos pequeñas glándulas sobre los riñones que producen adrenalina y cortisol.", full: "Corteza: glucocorticoides (cortisol), mineralocorticoides (aldosterona), andrógenos. Médula: catecolaminas (adrenalina y noradrenalina — respuesta de lucha o huida)." },
      { name: "Páncreas Endócrino", emoji: "🟩", color: "#16a34a", simple: "La parte endócrina del páncreas controla el azúcar en la sangre con insulina y glucagón.", full: "Los islotes de Langerhans contienen células beta (insulina: reduce glucemia) y alfa (glucagón: aumenta glucemia). La diabetes tipo 1 destruye células beta." },
      { name: "Gónadas", emoji: "🌸", color: "#f472b6", simple: "Son los ovarios (en mujeres) y los testículos (en hombres): producen hormonas sexuales.", full: "Ovarios: producen estrógenos y progesterona bajo control de FSH/LH. Testículos: producen testosterona (células de Leydig) que regula espermatogénesis y caracteres masculinos." },
      { name: "Paratiroides", emoji: "🟡", color: "#facc15", simple: "Son cuatro glándulas pequeñas que controlan el calcio en la sangre.", full: "Cuatro glándulas en la cara posterior del tiroides. Las células principales producen PTH cuando baja el calcio sérico. PTH activa osteoclastos, estimula reabsorción renal de Ca²⁺ y activa vitamina D." },
      { name: "Glándula Pineal", emoji: "🌙", color: "#6366f1", simple: "Es una glándula pequeña del cerebro que produce melatonina y regula el sueño.", full: "Produce melatonina a partir de serotonina en respuesta a la oscuridad. Sincroniza los ritmos circadianos (ciclo sueño-vigilia)." },
    ],
  },
  // ── Sistema Reproductor Femenino ──────────────────────────
  {
    slug: "reproductor",
    uid: "2ad78b1785c94bac83dcb623b53748f5",
    title: "Sistema Reproductor Femenino",
    subtitle: "♀ Anatomía Femenina",
    accent: "#f472b6",
    intro: "El sistema reproductor femenino produce óvulos y alberga el desarrollo del embrión. Explorá ovarios, útero, ciclo menstrual y fecundación en 3D.",
    structures: [
      { name: "Ovarios", emoji: "🌸", color: "#f472b6", simple: "Son dos órganos que producen los óvulos y las hormonas femeninas.", full: "Par de glándulas de ~3×2 cm. Contienen folículos ováricos en distintos estadios. Producen estrógenos y progesterona bajo control hipofisario (FSH/LH)." },
      { name: "Trompa de Falopio", emoji: "〰️", color: "#fb7185", simple: "Es el tubo que lleva el óvulo desde el ovario hasta el útero. Aquí ocurre la fecundación.", full: "Conducto muscular de ~10 cm con 4 segmentos: infundíbulo (fimbrias), ampolla (sitio de fecundación), istmo y parte uterina." },
      { name: "Útero", emoji: "🫙", color: "#e879f9", simple: "Es el órgano donde se desarrolla el bebé durante el embarazo.", full: "Órgano muscular hueco de ~7×5 cm (no gestante). Tres capas: endometrio, miometrio y perimetrio. El cuello uterino (cérvix) conecta con la vagina." },
      { name: "Endometrio", emoji: "🔴", color: "#c026d3", simple: "Es el revestimiento interno del útero donde se implanta el embrión.", full: "Mucosa uterina con capa funcional (se desprende en la menstruación) y basal (regenera la funcional). Responde a estrógenos y progesterona." },
      { name: "Folículo Ovárico", emoji: "🟡", color: "#f59e0b", simple: "Es la estructura en el ovario que contiene al óvulo mientras madura.", full: "Desarrollo: primordial → primario → secundario → antral → folículo de Graaf (preovulatorio). El pico de LH desencadena la ovulación." },
      { name: "Cuerpo Lúteo", emoji: "🟠", color: "#ea580c", simple: "Es lo que queda del folículo tras liberar el óvulo: produce progesterona para preparar el útero.", full: "Estructura glandular temporal que produce progesterona durante la fase lútea (~14 días). Sin embarazo, degenera. Con embarazo, la hCG lo mantiene." },
      { name: "Ciclo Menstrual", emoji: "🔄", color: "#ec4899", simple: "Es el proceso mensual del cuerpo femenino que prepara al útero para un posible embarazo.", full: "Dura ~28 días. Fase menstrual (días 1-5), folicular (días 1-13), ovulatoria (día 14: pico de LH), lútea (días 15-28: progesterona prepara el endometrio)." },
      { name: "Fecundación y Cigoto", emoji: "✨", color: "#a855f7", simple: "La fecundación es cuando el espermatozoide se une al óvulo y forman una sola célula nueva.", full: "Ocurre en la ampolla de la trompa. El espermatozoide atraviesa la zona pelúcida y se fusiona con el oocito II. Se forman 2 pronúcleos y nace el cigoto (2n = 46 cromosomas)." },
    ],
  },
  // ── Sistema Reproductor Masculino ────────────────────────
  {
    slug: "reproductor-masculino",
    uid: "035316622877438cb62de673b8f19217",
    title: "Sistema Reproductor Masculino",
    subtitle: "♂ Anatomía Masculina",
    accent: "#60a5fa",
    intro: "El sistema reproductor masculino produce espermatozoides y la hormona testosterona. Explorá testículos, epidídimo, próstata y fecundación en 3D.",
    structures: [
      { name: "Testículos", emoji: "🔵", color: "#3b82f6", simple: "Son los órganos que producen los espermatozoides y la testosterona.", full: "Par de glándulas ovoides dentro del escroto (~4×3 cm). Los túbulos seminíferos contienen células de Sertoli (nutren espermatozoides) y células de Leydig (producen testosterona)." },
      { name: "Epidídimo", emoji: "〰️", color: "#60a5fa", simple: "Es el tubo enroscado donde los espermatozoides maduran y aprenden a moverse.", full: "Conducto muy enrollado de ~6 m adosado al testículo. Los espermatozoides completan su maduración en ~12-21 días, adquiriendo motilidad y capacidad de fertilización." },
      { name: "Conducto Deferente", emoji: "➡️", color: "#2563eb", simple: "Es el tubo que transporta los espermatozoides hasta la uretra durante la eyaculación.", full: "Conducto muscular de ~45 cm que sube por el cordón espermático. La vasectomía lo secciona como método anticonceptivo." },
      { name: "Vesícula Seminal", emoji: "🟣", color: "#7c3aed", simple: "Son glándulas que producen la mayor parte del líquido del semen.", full: "Par de glándulas que producen ~65% del volumen del semen: fructosa (energía), prostaglandinas y vitamina C. Reguladas por testosterona." },
      { name: "Próstata", emoji: "⚙️", color: "#4f46e5", simple: "Es una glándula que produce líquido que protege a los espermatozoides y les ayuda a moverse.", full: "Glándula de ~20 g que rodea la uretra. Secreta ~30% del semen con PSA, zinc y citrato. El PSA es marcador de cáncer de próstata." },
      { name: "Pene y Uretra", emoji: "🔷", color: "#0ea5e9", simple: "El pene es el órgano copulador. La uretra es el canal compartido por orina y semen.", full: "El pene contiene 3 cuerpos eréctiles. La erección ocurre por vasodilatación mediada por óxido nítrico. La uretra masculina (~20 cm) conduce orina y eyaculado." },
      { name: "Espermatozoide", emoji: "🏊", color: "#38bdf8", simple: "Es la célula sexual masculina: muy pequeña, con cola para nadar hasta el óvulo.", full: "Célula haploide (23 cromosomas) de ~55 µm. Cabeza: núcleo + acrosoma (enzimas). Cuello: mitocondrias. Cola (flagelo): propulsión. Sobreviven 3-5 días en el tracto femenino." },
      { name: "Testosterona y Eje Hormonal", emoji: "⚗️", color: "#818cf8", simple: "La testosterona es la hormona masculina principal. El cerebro la regula enviando señales a los testículos.", full: "Eje hipotálamo-hipófisis-testículos: GnRH → LH y FSH → testosterona (células de Leydig). Retroalimentación negativa. Promueve caracteres sexuales secundarios y libido." },
    ],
  },
  // ── Órganos de los Sentidos ───────────────────────────────
  {
    slug: "sentidos",
    uid: "f80bda64666c4b8aaac8f63b7b82a0a0",
    title: "Órganos de los Sentidos",
    subtitle: "👁️ Vista, Oído y Más",
    accent: "#22d3ee",
    intro: "Los órganos de los sentidos captan información del entorno y la envían al cerebro. Explorá la anatomía del ojo y el oído en 3D.",
    structures: [
      { name: "Córnea", emoji: "👁️", color: "#e0f2fe", simple: "Es la capa transparente delantera del ojo que deja entrar la luz.", full: "Tejido avascular transparente de 5 capas. Proporciona ~2/3 del poder refractivo del ojo (~43 dioptrías). Muy inervada y sensible al tacto." },
      { name: "Iris y Pupila", emoji: "🔵", color: "#38bdf8", simple: "El iris es el anillo de color del ojo. La pupila es el hueco negro que cambia de tamaño con la luz.", full: "Iris: diafragma muscular pigmentado. Músculo esfínter pupilar: contrae la pupila (miosis). Músculo dilatador: dilata (midriasis) en oscuridad." },
      { name: "Cristalino", emoji: "🔍", color: "#7dd3fc", simple: "Es la lente del ojo que enfoca los objetos, tanto los cercanos como los lejanos.", full: "Lente biconvexa avascular y transparente. La acomodación (cambio de forma) permite enfocar objetos a distintas distancias. Con la edad pierde elasticidad (presbicia)." },
      { name: "Retina", emoji: "🟡", color: "#fbbf24", simple: "Es la pantalla del ojo donde se forman las imágenes que luego van al cerebro.", full: "Capa neural de 10 estratos. Contiene ~120 millones de bastones (visión blanco/negro) y ~6 millones de conos (visión de color). La fóvea central tiene alta densidad de conos." },
      { name: "Nervio Óptico", emoji: "🟣", color: "#a855f7", simple: "Es el cable que lleva la imagen desde el ojo hasta el cerebro.", full: "Par craneal II. Formado por ~1,2 millones de axones. Los nervios ópticos se cruzan en el quiasma óptico. Las señales llegan al cuerpo geniculado lateral y luego a la corteza visual." },
      { name: "Tímpano y Oído Externo", emoji: "👂", color: "#f97316", simple: "El tímpano es la membrana que vibra cuando llegan sonidos al oído.", full: "Oído externo: pabellón auricular + conducto auditivo externo. El tímpano (~10 mm de diámetro) vibra con las ondas sonoras y transmite la vibración a los huesecillos." },
      { name: "Martillo, Yunque y Estribo", emoji: "🦴", color: "#ea580c", simple: "Son los tres huesecillos más pequeños del cuerpo que amplifican el sonido.", full: "Los tres osículos del oído medio forman una cadena mecánica. El martillo se une al tímpano; el estribo transmite la vibración a la ventana oval. Amplifican el sonido ~22 veces." },
      { name: "Cóclea", emoji: "🐌", color: "#10b981", simple: "Es la caracola del oído interno que convierte las vibraciones de sonido en señales eléctricas.", full: "Estructura espiral con 2,5 vueltas. El órgano de Corti contiene ~16.000 células ciliadas que detectan frecuencias específicas (tonotopía). Las señales van al nervio coclear (VIII par)." },
      { name: "Sistema Vestibular", emoji: "⚖️", color: "#0ea5e9", simple: "Es la parte del oído interno que nos dice si estamos en equilibrio o si nos movemos.", full: "Incluye utrículo, sáculo (aceleración lineal y gravedad) y 3 canales semicirculares (aceleración angular). Las células ciliadas transducen el movimiento." },
    ],
  },
  // ── Microbiología ─────────────────────────────────────────
  {
    slug: "microbiologia",
    uid: "4a310db79e834e07a69ee8d4892d46ee",
    title: "Microbiología",
    subtitle: "🦠 Bacterias y Microorganismos",
    accent: "#4ade80",
    intro: "Las bacterias son los seres vivos más abundantes del planeta. Explorá la estructura de una bacteria E. coli en 3D.",
    structures: [
      { name: "Membrana Plasmática", emoji: "🟢", color: "#4ade80", simple: "Es la capa que rodea a la bacteria y controla qué entra y qué sale.", full: "Bicapa lipídica de fosfolípidos sin colesterol. Contiene proteínas de transporte y enzimas de la cadena respiratoria. La diferencia con la membrana eucariota la convierte en diana de antibióticos." },
      { name: "Pared Celular", emoji: "🟩", color: "#22c55e", simple: "Es la capa dura que protege a la bacteria y le da su forma característica.", full: "Compuesta de peptidoglucano (murena). Gram positivas: pared gruesa de peptidoglucano. Gram negativas: pared delgada + membrana externa con LPS. La penicilina ataca la síntesis de peptidoglucano." },
      { name: "Nucleoide", emoji: "🔵", color: "#3b82f6", simple: "Es la zona donde está el ADN de la bacteria: no tiene membrana alrededor.", full: "Región nuclear no delimitada por membrana. Contiene un único cromosoma circular de ADN de doble cadena (~4,6 Mb en E. coli) asociado a proteínas HU y H-NS." },
      { name: "Ribosoma 70S", emoji: "🟡", color: "#fbbf24", simple: "Son las fábricas de proteínas de la bacteria, más pequeñas que las de nuestras células.", full: "Los ribosomas bacterianos son 70S (subunidades 30S + 50S), más pequeños que los eucarióticos (80S). Aminoglucósidos, macrólidos y tetraciclinas bloquean selectivamente su síntesis proteica." },
      { name: "Flagelo Bacteriano", emoji: "〰️", color: "#a3e635", simple: "Es la 'cola' que usa la bacteria para moverse como un motor.", full: "Filamento proteico helicoidal compuesto por flagelina. El cuerpo basal actúa como motor rotatorio impulsado por el gradiente de protones. La quimiotaxis usa el movimiento flagelar." },
      { name: "Pili y Fimbrias", emoji: "🔴", color: "#f87171", simple: "Son pequeños 'pelos' que usa la bacteria para pegarse a superficies o intercambiar ADN.", full: "Fimbrias/pili tipo I: permiten adhesión a tejidos del huésped. Pili sexuales: transfieren plásmidos de ADN entre bacterias (conjugación). Clave en la diseminación de resistencias antibióticas." },
      { name: "Cápsula Bacteriana", emoji: "🫧", color: "#d9f99d", simple: "Es una capa gelatinosa alrededor de algunas bacterias que las protege del sistema inmune.", full: "Capa de polisacáridos que rodea algunas bacterias. Inhibe la fagocitosis por macrófagos y neutrófilos. Es un factor de virulencia importante. Base de vacunas polisacáridas conjugadas." },
      { name: "Plásmidos y Resistencia", emoji: "🧬", color: "#86efac", simple: "Son pequeños anillos de ADN extra que pueden darle a la bacteria resistencia a antibióticos.", full: "Moléculas de ADN circular extracromosómico. Pueden contener genes de resistencia a antibióticos, toxinas y virulencia. Se replican independientemente y se transfieren por conjugación o transformación." },
    ],
  },
  // ── Ecosistemas ───────────────────────────────────────────
  {
    slug: "ecosistemas",
    uid: "fd32a91331f048be9b94cf0cb8c312ed",
    title: "Ecosistemas",
    subtitle: "🌳 Ecología y Biodiversidad",
    accent: "#22c55e",
    intro: "Un ecosistema es la red de relaciones entre los seres vivos y su ambiente. Explorá cadenas alimentarias, niveles tróficos y ciclos de la materia.",
    structures: [
      { name: "Productores (Plantas y Algas)", emoji: "🌿", color: "#4ade80", simple: "Son los seres vivos que fabrican su propio alimento con la luz solar.", full: "Organismos autótrofos fotosintetizadores que convierten CO₂ + H₂O + luz solar en glucosa y O₂. Base de todas las cadenas alimentarias. Representan el primer nivel trófico." },
      { name: "Consumidores Primarios (Herbívoros)", emoji: "🐰", color: "#86efac", simple: "Son los animales que comen directamente las plantas.", full: "Primer nivel de consumidores heterótrofos. Solo el ~10% de la energía del nivel anterior se transfiere. La biomasa disminuye a lo largo de la cadena." },
      { name: "Consumidores Secundarios (Carnívoros)", emoji: "🦊", color: "#22c55e", simple: "Son los animales que comen a los herbívoros.", full: "Segundo nivel de consumidores. Se alimentan de herbívoros. Regulan las poblaciones de herbívoros evitando el sobrepastoreo." },
      { name: "Consumidores Terciarios (Superdepredadores)", emoji: "🦅", color: "#16a34a", simple: "Son los depredadores del tope: no los caza nadie más.", full: "Tercer nivel de consumidores. Regulan toda la cadena trófica (efecto cascada trófica). Su extinción causa explosión de poblaciones en niveles inferiores." },
      { name: "Descomponedores", emoji: "🍄", color: "#bbf7d0", simple: "Son hongos y bacterias que 'reciclan' la materia de los seres muertos.", full: "Hongos y bacterias saprofíticos que descomponen la materia orgánica muerta liberando CO₂, agua y minerales al suelo. Son el cierre de los ciclos biogeoquímicos." },
      { name: "Flujo de Energía", emoji: "⚡", color: "#fbbf24", simple: "La energía del sol fluye por los seres vivos de un nivel al siguiente, pero se pierde a cada paso.", full: "La energía solar entra por la fotosíntesis. En cada nivel trófico se pierde ~90% como calor. Solo ~10% se incorpora a la biomasa del siguiente nivel (regla del 10%)." },
      { name: "Ciclo del Carbono", emoji: "🔄", color: "#65a30d", simple: "El carbono pasa de la atmósfera a los seres vivos y vuelve al aire en un ciclo continuo.", full: "El CO₂ se fija por fotosíntesis → materia orgánica → pasa por la cadena trófica → vuelve como CO₂ por respiración, descomposición y combustión. La quema de fósiles altera el ciclo." },
      { name: "Biodiversidad y Biomas", emoji: "🗺️", color: "#166534", simple: "La biodiversidad es la variedad de seres vivos; los biomas son las grandes zonas del planeta.", full: "Biodiversidad: genética, específica y ecosistémica. A mayor biodiversidad → mayor estabilidad. Biomas principales: selva tropical, sabana, desierto, tundra, bosque templado, oceanos." },
    ],
  },
  // ── Herencia Genética ─────────────────────────────────────
  {
    slug: "herencia",
    uid: "4d57784b0d4841d0ab3d43d526df1c3f",
    title: "Herencia Genética",
    subtitle: "🧬 Genética y Transmisión de Caracteres",
    accent: "#f59e0b",
    intro: "La herencia genética explica cómo los padres transmiten sus características a los hijos. Explorá el ADN, los cromosomas y las leyes de Mendel.",
    structures: [
      { name: "Gen y Alelo", emoji: "🧩", color: "#f59e0b", simple: "Un gen es la 'instrucción' para una característica; los alelos son las versiones distintas de ese gen.", full: "Gen: secuencia de ADN que codifica una proteína. Los seres diploides tienen 2 alelos de cada gen. Homocigoto (AA o aa) vs. heterocigoto (Aa). El alelo dominante se expresa sobre el recesivo." },
      { name: "Genotipo y Fenotipo", emoji: "🔤", color: "#d97706", simple: "El genotipo es la combinación de alelos que tiene el organismo; el fenotipo es la característica que se ve.", full: "Genotipo: composición alélica real (AA, Aa, aa). Fenotipo: expresión observable producto del genotipo + ambiente. Dos individuos con igual fenotipo pueden tener genotipos distintos." },
      { name: "Leyes de Mendel", emoji: "📋", color: "#b45309", simple: "Mendel descubrió las reglas básicas de cómo se heredan los caracteres.", full: "1ª ley: Uniformidad (todos los F1 iguales). 2ª ley: Segregación (3:1 en F2). 3ª ley: Segregación independiente (genes en distintos cromosomas se heredan independientemente → 9:3:3:1 en dihíbrido)." },
      { name: "Cuadro de Punnett", emoji: "🔲", color: "#78350f", simple: "Es una tabla que predice qué genotipos son posibles en los hijos de un cruce.", full: "Los gametos del padre en columnas y los de la madre en filas. Para un cruce Aa × Aa: 1 AA (25%) : 2 Aa (50%) : 1 aa (25%) = fenotipo 3:1. Base para calcular probabilidades de herencia de enfermedades." },
      { name: "Dominancia y Codominancia", emoji: "⬆️", color: "#92400e", simple: "Dominante: el alelo que 'gana' y se expresa siempre. En codominancia, los dos alelos se expresan juntos.", full: "Dominancia completa: A enmascara a. Codominancia: ambos alelos se expresan (ej: IAIB = grupo AB). Dominancia incompleta: heterocigoto tiene fenotipo intermedio (ej: flor roja × blanca → rosa)." },
      { name: "Herencia Ligada al Sexo", emoji: "🔀", color: "#a16207", simple: "Es la herencia de genes que están en los cromosomas sexuales X o Y.", full: "Genes del cromosoma X se expresan sin contraparte en varones (XY). Enfermedades recesivas ligadas al X (daltonismo, hemofilia) son más frecuentes en hombres. Las mujeres pueden ser portadoras." },
      { name: "Mutación Genética", emoji: "⚡", color: "#d97706", simple: "Una mutación es un cambio en el ADN. Puede ser heredada y afectar a los hijos.", full: "Cambio en la secuencia de ADN. Tipos: puntual (sustitución, inserción, deleción), cromosómica (translocación, inversión) y genómica (poliploidía). Los mutágenos (UV, radiación X) aumentan su frecuencia." },
      { name: "Cromosoma y Cariotipo", emoji: "🧵", color: "#fbbf24", simple: "Los cromosomas son los 'paquetes' donde está guardado el ADN. Los humanos tenemos 46 (23 pares).", full: "Los humanos tienen 2n=46 cromosomas: 22 pares de autosomas + 1 par sexual (XX femenino, XY masculino). La trisomía 21 (síndrome de Down) surge por no disyunción en la meiosis." },
    ],
  },
];

export function getModule(slug: string): ModuleData | undefined {
  return MODULES.find(m => m.slug === slug);
}
